# Generated by Django 2.2.3 on 2019-09-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainscreen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
