# Generated by Django 2.2.3 on 2019-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_pw', models.CharField(max_length=15)),
                ('user_nk', models.CharField(max_length=15)),
                ('user_em', models.CharField(max_length=20)),
                ('user_ph1', models.CharField(max_length=3)),
                ('user_ph2', models.CharField(max_length=4)),
                ('user_ph3', models.CharField(max_length=4)),
            ],
        ),
    ]
