# Generated by Django 2.2.3 on 2019-10-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_name',
            new_name='user_realname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_nickname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_password',
        ),
    ]
