# Generated by Django 2.2.3 on 2019-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191001_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isdesigner',
            field=models.BooleanField(default=False),
        ),
    ]
