# Generated by Django 2.2.6 on 2019-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(choices=[('ill', 'illustration'), ('cha', 'character'), ('por', 'portrait'), ('cal', 'calligraphy'), ('web', 'webtoon'), ('vid', 'video'), ('oth', 'other')], max_length=3),
        ),
    ]
